---
title: "WW8_6/8_Data"
author: "Prashant Kalvapalle"
date: "10 June 2020"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 8, fig.height = 4)
```

## Goal of the analysis

Quantifying recovery of spiked bovine CoV vaccine and comparison between variants of HA filtration method

## Plots
### Raw copy #

```{r sourcing}
source('general_functions.R')

flnm <- 'WW8_608_N1 N2 BCoV'  # set the filename
results_abs <- read_sheet('https://docs.google.com/spreadsheets/d/1ouk-kCJHERRhOMNP07lXfiC3aGB4wtWXpnYf5-b2CI4/edit#gid=0', sheet = flnm) # retrieve saved results from the google sheet

# plotting
summary_results_abs <- results_abs %>%  group_by(`Sample Name`, Target, assay_variable, WWTP) %>% summarise_at(vars(`Copy #`), funs(mean(.,na.rm = T), sd(., na.rm = T))) # find mean and SD of individual copy #s for each replicate
results_abs %<>% replace_na(replace = list('Copy #' = 0, Recovered = 0)) # Make unamplified values zero: for plotting - not counted in the mean calculations

plt <- summary_results_abs %>% ggplot(aes(x = WWTP, y = mean, color = Target)) + ylab('Copies/ul RNA extract')    # Specify the plotting variables 

plt <- plt + geom_errorbar(aes(ymin = mean -sd, ymax = mean + sd, width = errorbar_width)) + # plot errorbars if mean and SD are desired
  geom_jitter(data = results_abs, aes(x = WWTP, y = `Copy #`, colour = Target), size = 1, width = .2) + # plot raw data
  geom_point(size = 2) +
  facet_grid(~`Sample Name`, scales = 'free_x', space = 'free_x') # plot points and facetting

# Formatting plot
plt.formatted <- plt %>% format_classic(., title_name, 'WWTP or Sample name') %>% format_logscale() # formatting plot, axes labels, title and logcale plotting

print(plt.formatted)
```

### Recovery vs expected

```{r reco}
# concise_summary <- summary_results_abs %>% select(-assay_variable) %>% gather(key = 'Measurement', value = 'Reading', -Target, -`Sample Name`, -WWTP) # get data into long for
# concise_raw <- results_abs %>% select(3:4,7:11,13:15) %>% gather(key = 'Measurement', value = 'val', -Target, -`Sample Name`, -`Tube ID`, -WWTP, -`FACILITY NAME`) # Seperate mean and variance and group by variable of measurement

```


## Data output

```{r summarydatadisplay}
summary_results_abs %<>% mutate_if(is.numeric, format, digits = 3, scientific = T)
kable(summary_results_abs, caption = 'Summary of estimated copy #s')
```

### Individual replicates
```{r datadisplay}
results_abs %<>% mutate_if(is.numeric, format, digits = 3, scientific = T)
kable(results_abs, caption = 'Raw data and estimated copy #s')
```
