---
title: "Weekly comparisons"
author: "Prashant Kalvapalle"
date: "7 July 2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 6, fig.height = 4)

# Loading libraries, functions and user inputs
source('./general_functions.R') # Source the general_functions file
source('./inputs_for_analysis.R') # Source the file with user inputs

# sheets to read from "qPCR data to present + recoveries"" google sheet
read_these_sheets <- c('WW27_Test pMMoV', '615 Rice', '622 Rice', '629 Rice') # sheet name(s) in the raw data file (qPCR data dump) - Separate by comma (,)
title_name <- 'June Rice' # name of the filename for writing presentable data and plot title

# Extra categories to exclude from plotting (separate by | like this 'Vaccine|Troubleshooting')
extra_categories = 'Std|Vaccine|NTC|TR|Blank'
```

## Recovery | Density plot

```{r}
# Acquire all the pieces of the data : read saved raw qPCR results from a google sheet
list_rawqpcr <- map(read_these_sheets, ~ read_sheet('https://docs.google.com/spreadsheets/d/1ltvW7xZf2aUPoBchD4NFGuV0gGWPkdsOW3a0Hxalm-Y/edit#gid=1363292517', sheet = .x) %>%  
                      mutate('Week' = str_match(.x, '(6.*) ') %>% .[,2]) %>%
                      rename('Target' = matches('Target'), 'Original Sample Volume' = matches('WW_vol|Original Sample Volume'), 'Ct' = matches('^CT', ignore.case = T)) %>% 
                       mutate_at('Target', ~str_replace_all(., c('.*N1.*' = 'SARS CoV-2 N1', '.*N2.*' = 'SARS CoV-2 N2')))

                      ) 

rawqpcr <- bind_rows(list_rawqpcr) %>% mutate_at('Week', ~if_else(is.na(.), Date, Week))
results_abs <- rawqpcr %>% filter(!str_detect(Facility, extra_categories)) %>%  # remove unnecessary data
  mutate_at('Week', ~ factor(.))

# fixing a sample artificially removed due to qPCR miscalling CT : UB 622
results_abs$`Copies/l WW`[22] %<>% if_else(is.na(.), 0, .)

results_abs %>% ggplot(aes(x = Week, y = `Recovery fraction`)) + geom_jitter(width = .1)
```

## Recovery | Dot plot

```{r dots}

nameless <- results_abs %>% select(Week, `Recovery fraction`) %>% drop_na() %>% group_by(Week) %>% arrange(`Recovery fraction`) %>%  mutate(id = row_number()) 

nameless %>% ggplot(aes(x = id, y = `Recovery fraction`, colour = Week)) + geom_point() + geom_line()
```

## N comparisions | Scatter

```{r}

results_wide <- results_abs %>% select(WWTP, Target, Week, `Copies/l WW`) %>% group_by(Week, Target, WWTP) %>% mutate(id = row_number()) %>% unite('WWTP', c('WWTP', id)) %>% pivot_wider(names_from = Target, values_from = `Copies/l WW`) 

results_wide %>% ggplot(aes(x = `SARS CoV-2 N1`, y = `SARS CoV-2 N2`, colour = Week)) + geom_point() + geom_smooth(method = 'lm') 
```

## pMMoV vs other targets

```{r, fig.width= 12, fig.height= 4}

pmmov_relevant <- results_wide %>% drop_na(pMMoV_Vgp1) %>% pivot_longer(cols = c(3:7), names_to = 'Target', values_to = 'Copies/l WW') %>% separate(WWTP, into = c('WWTP', NA))

plt_pmm <- pmmov_relevant %>% ggplot(aes(x = Week, y = `Copies/l WW`, colour = Target)) + geom_point() + geom_line(aes(group = Target)) + facet_grid(~ WWTP, space = 'free_x', scales = 'free_x')

plt_pmm %>% format_logscale_y() %>% format_classic() %>% print()

```
